version: '3.9'

services:
  c5:
    build: .
    ports:
      - 4000:80


  jenkins:
    image: jenkins/jenkins:lts
    privileged: true      
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    container_name: jenk
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 

  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa Q2ryIs+MDZfGjIt7JTtH7O9sRHXrV9j5Ny7wfWLS/oI cynapsys0\mokhles.jaziri@ITMTN27DGMW
  